spring.datasource.url = ${DB_URL:jdbc:postgresql://localhost:5432/smartEcom}
spring.datasource.username =${DB_USERNAME:postgres}
spring.datasource.password = ${DB_PASSWORD:Drake@7890}
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql = true
spring.datasource.driver-class-name = org.postgresql.Driver

# Logging levels
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.com.amalitech.demo=DEBUG
