spring.datasource.url = jdbc:postgresql://localhost:5432/smartEcom
spring.datasource.username = postgres
spring.datasource.password = Drake@7890
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
