spring.application.name=smart ecom system
spring.profiles.active=dev
graphql.grahiql.enabled=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# CORS configuration for frontend origins (comma-separated list)
app.cors.allowed-origins=http://localhost:3000
