spring.application.name=smart ecom system
spring.profiles.active=test
graphql.grahiql.enabled=true
#spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# CORS configuration for frontend origins (comma-separated list)
app.cors.allowed-origins=http://localhost:3000

spring.security.oauth2.client.registration.google.client-id=926588561982-92o86imidoqkcu2cgfo7inemv5c1pspf.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
logging.level.org.springframework.security=DEBUG