spring.application.name=smart ecom system
spring.profiles.active=test
graphql.grahiql.enabled=true
#spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# CORS configuration for frontend origins (comma-separated list)
app.cors.allowed-origins=http://localhost:3000

# JWT Configuration
security.jwt.secret=change-me-secret-key-change-me-secret-key-change-me-secret-key
security.jwt.issuer=demo-app
app.jwt.expiration=900000

spring.security.oauth2.client.registration.google.client-id={CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret={CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
logging.level.org.springframework.security=DEBUG
app.oauth2.redirect-uri=http://localhost:3001/oauth2/redirect
# Actuator / Micrometer
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
